### ISSUE TITLE
Data at root level is invalid, generating xlsx from linux with mono

### ISSUE THREAD

**Issue by devel0** [ClosedXML/ClosedXML#14]
I tried to gen a simple xlsx

```csharp
var wb = new XLWorkbook();

var ws = wb.Worksheets.Add("test");
ws.Cell(1, 1).Value = 101.23;

wb.SaveAs("test.xlsx");
```

running the above sample under windows I get a working xlsx file, if I generate that using latest mono under linux I get an error opening the xlsx that ask me to repair.

I tried to open that using OpenXML Tool v2.5 and results follow error

> "Cannot open the file. Data at the root level is invalid. Line 1, position 681."

More, I tried to generate a basic xlsx file directly using Documentformat.OpenXml and that error not happens. I found [this blog](http://madskristensen.net/post/data-at-the-root-level-is-invalid) describing this error in another situation but may useful to investigate in a possible solution.

Attached two generated xlsx files.
[win-test.xlsx](https://github.com/ClosedXML/ClosedXML/files/464914/win-test.xlsx)
[linux-test.xlsx](https://github.com/ClosedXML/ClosedXML/files/464915/linux-test.xlsx)

I'm available todo tests from any branch of the ClosedXML repository if needed agains execution under linux, by the way its easy to try that using ubuntu 16.04 lts after an `apt-get install mono-complete` just run `mono my-test.exe` to see the behavior.

**Comment by igitur** [comment]
I can reproduce the error on Mono. The problem is that the `/xl/_rels/workbook.xml.rels` is malformed. The contents of the file ends with `</Relationships>s>` , which is clearly malformed XML. 

The malformed XML is introduced when there is no calculation chain. ClosedXML deletes the relevant XML element `<Relationship Id="rId5" Target="/xl/calcChain.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/calcChain" />` (`.DeletePart`) when there is no calculation chain. The deletion of this element leaves some characters behind (probably some buffer issue). I'm pretty confident that it's a bug in the XML serialization part of Mono. 

I'll see whether there's an easy workaround, but many parts of ClosedXML follow similar logic and would delete XML elements. There are probably other places where this bug will creep in.

**Comment by vbjay** [comment]
Nice work tracing it down.  I would submit a bug to the openxmlsdk and mono
projects.  Considering it works fine on windows, i'm sure it is a mono and
not openxmlsdk issue.

**Comment by igitur** [comment]
Found the bug in `WindowsBase`. It has been solved in https://github.com/mono/mono/commit/aae26db0c28a0e8e6241d523ac006ae8e9047916

**Comment by Pyropace** [comment]
Great discussion guys, i just came online to test for this bug, but seems like igitur has beat me to it ;)

**Comment by devel0** [comment]
I confirm the https://github.com/mono/mono/commit/aae26db0c28a0e8e6241d523ac006ae8e9047916 is the commit that solved the bug ( tried from source build ).

I should have checked a [nightly builds](http://www.mono-project.com/docs/getting-started/install/weekly-packages/) to see it's already fixed while I used the current `mono-complete` from ubuntu 16.04 that's not yet sync'ed with these fixes.

Thanks

**Comment by igitur** [comment]
A stupid workaround would be to include at least one formula somewhere in the workbook.

**Comment by ofenloch** [comment]
I still have that problem when I try to run the unit tests under Linux. I had to install mono to get the tests running at all (see output below). 

My mono version is:

      ofenloch@3fb1caa5b6d0:~/workspaces/dotnet/ClosedXML$ mono -V
      Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
      Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
      ofenloch@3fb1caa5b6d0:~/workspaces/dotnet/ClosedXML$

Output of `dotnet test`:

```bash
Test run for /home/ofenloch/workspaces/dotnet/ClosedXML/ClosedXML.Tests/bin/Debug/net461/ClosedXML.Tests.dll (.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed CustomAutoFilter [238 ms]
  Error Message:
   System.Xml.XmlException : Root element is missing.
  Stack Trace:
    at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <32c3e38f366e434db513ac7ca6d10f6c>:0 
  at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <32c3e38f366e434db513ac7ca6d10f6c>:0 
...
...
Failed!  - Failed:   124, Passed:  3104, Skipped:    13, Total:  3241, Duration: 59 s - /home/ofenloch/workspaces/dotnet/ClosedXML/ClosedXML.Tests/bin/Debug/net461/ClosedXML.Tests.dll (net461)
```
