### ISSUE TITLE
[Could not load type 'DocumentFormat.OpenXml.Packaging.IdPartPair']

### ISSUE THREAD

**Issue by nsnhan127** [ClosedXML/ClosedXML#2220]
In my project, I use 2 packages: ClosedXML ver 0.102.1 and DocumentFormat.OpenXml ver 3.0.0. I encountered an error when using ClosedXML to create an excel file (image below)
![image](https://github.com/ClosedXML/ClosedXML/assets/39818300/a2082e17-9bbd-4187-94ff-ea8ae1387098)

and error is : "Could not load type 'DocumentFormat.OpenXml.Packaging.IdPartPair' from assembly 'ClosedXML, Version=0.102.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b' due to value type mismatch."

How can i fix this issue ?

**Comment by TonyHenrique** [comment]
I also have just started to get this error when I call XLWorkbook SaveAs:

`System.TypeLoadException: 'Could not load type 'DocumentFormat.OpenXml.Packaging.IdPartPair' from assembly 'ClosedXML, Version=0.102.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b' due to value type mismatch.'
`

**Comment by marcosgerene** [comment]
Same here.

I tried to update to preview version and the problem still happens.

----

I downgraded from dotNet8 to dotNet6 and it works fine.

**Comment by TonyHenrique** [comment]
I think that I also had DocumentFormat.OpenXml version 3.0.0
I removed it and now ClosedXML it is working again here on .NET 8

**Comment by nsnhan127** [comment]
In my case, I found a solution, I lowered the version of Document.OpenXML to version 2.16.0, I no longer got the error. Hope everyone will have success with this solution

**Comment by marcosgerene** [comment]
My application was setted to 2.16 and still having problems.

I had to downgrade to dotnet6 to fix it.

**Comment by donalddps** [comment]
@nsnhan127 can we keep this issue open or make another issue specficially for OpenXML 3.0 support? I had to downgrade OpenXML referenced in one project because it was incompatible with ClosedXML (tried the latest preview build of ClosedXML and same issue) referenced in another project.

My issue specifically was this call:
`var workbook = new XLWorkbook(templatePath);`

Which throws the MissingMethodException:

> Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.

Downgrading OpenXML, while it may fix the issue, isn't a long-term solution.

**Comment by nsnhan127** [comment]
@donalddps ok, I reopened this issue for everyone who have a better solution for any case.

**Comment by odobrovolny-IDG** [comment]
> I also have just started to get this error when I call XLWorkbook SaveAs:
> 
> `System.TypeLoadException: 'Could not load type 'DocumentFormat.OpenXml.Packaging.IdPartPair' from assembly 'ClosedXML, Version=0.102.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b' due to value type mismatch.' `

Hello everyone. I have exactly the same problem. We just upgraded to `.net8` and `ClosedXML version to 0.102.1` and this started happening. Thanks to you guys in this thread I managed to find, that downgrading `OpenXML to 2.20.0` "fixes" the issue
It makes me wonder though, did they change something in ClosedXML that i can change in my code to avoid downgrading? Maybe call different method or different overload?

**Comment by Deny01** [comment]
what's the base reason about this issue?

**Comment by davidkdb** [comment]
We have the same issue. Downgrading openXML solved it. We're also running on .NET 8.

**Comment by mariojsnunes** [comment]
Also facing the same issue. But downgrading OpenXML isn't an option as it's a peer dependency.

I'd guess updating the dependency to 3.0.0 would solve it:
https://github.com/ClosedXML/ClosedXML/blob/25eb3030e6c796df093f7e6ccdcb268dcd74b861/ClosedXML/ClosedXML.csproj#L36C5-L36C75
Any idea how difficult it is? I see a lot of breaking changes here...
https://github.com/dotnet/Open-XML-SDK/releases/tag/v3.0.0

**Comment by BieleckiLtd** [comment]
Would annotating compatible dependency version of OpenXml in ClosedXML help?

```
<PackageReference Include="DocumentFormat.OpenXml" Version="[2.16.0,3.0.0)" />
```

What this means ClosedXML accepts OpenXml 2.16.0 and up, but not 3.0.0 and higher. This should prevent it using 3.0.0 referenced by another dependency. [source](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges)

**Comment by jahav** [comment]
I have published a package 0.102.2 with explicit allowed version per @BieleckiLtd suggestion. ClosedXML isn't yet compatible with 3.0, so users will get a warning if they depend on it and it's sufficient stopgap for now. I have also pinned the issue.

![image](https://github.com/ClosedXML/ClosedXML/assets/7634052/24032cc6-10ab-450e-a36e-75d5fd3a313e)

**Comment by igitur** [comment]
thanks @jahav

What are the blockers for OpenXml 3.0.0 ? Is there an issue for that somewhere?

**Comment by jahav** [comment]
@igitur I took a quick look and I am waiting for 3.1, see #2248. I don't exactly remember what consequences of wrong `SpreadsheetDocumentType` , but I believe it strips some parts depending on the type (e.g. VBA parts from normal workbook).. Maybe?

**Comment by igitur** [comment]
> @igitur I took a quick look and I am waiting for 3.1, see #2248. I don't exactly remember what consequences of wrong `SpreadsheetDocumentType` , but I believe it strips some parts depending on the type (e.g. VBA parts from normal workbook).. Maybe?

Thanks. Yes, that definitely is a blocker!

**Comment by simonziegler** [comment]
I still get an exception. I use `ClosedXML` 0.102.2 and `DocumentFormat.OpenXml` 3.0.1.

```
System.TypeLoadException: Could not load type 'DocumentFormat.OpenXml.Packaging.IdPartPair' from assembly 'ClosedXML, Version=0.102.2.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b' due to value type mismatch.
```

**Comment by jahav** [comment]
@simonziegler And you are running incompatible major version for 0.102.2, as described in the issue (https://github.com/ClosedXML/ClosedXML/issues/2220#issuecomment-1878788277).

Update to OpenXML SDK 3.0 has been merged in #2248 for 0.104, so I am closing the issue.

**Comment by simonziegler** [comment]
> @simonziegler And you are running incompatible major version for 0.102.2, as described in the issue ([#2220 (comment)](https://github.com/ClosedXML/ClosedXML/issues/2220#issuecomment-1878788277)).
> 
> Update to OpenXML SDK 3.0 has been merged in #2248 for 0.104, so I am closing the issue.

Many thanks. I'll wait for this to be available on Nuget and will try again then.

Much appreciated, Simon

**Comment by Trapulo** [comment]
I still have the problem using 0.104.0-preview2 is this right?

**Comment by Kees-Schouten** [comment]
> problem

Yes me too!

**Comment by JadynWong** [comment]
`0.104.0-preview3` is still not available at nuget.

https://github.com/ClosedXML/ClosedXML/commit/3f4e251a5e0ae2cf3814d7de38389ee268375980

**Comment by mariojsnunes** [comment]
Is there an estimation for the next nuget release?
For us, this has been a dotnet8 migration blocker for a few months now.
Thanks for the hard work!

**Comment by jahav** [comment]
@mariojsnunes That is a self-imposed blocker, because you also updated OpenXML-SDK to a different major version. OpenXML SDK 2.* works fine on .NET8.

As for when, I am in middle (hopefully two thirds) of pivot tables refactoring and it doesn't go well. I hoped it would be done by now...

**Comment by mariojsnunes** [comment]
unfortunately for us it was another 3rd party dependency that updated OpenXML-SDK.
thanks for the update!

**Comment by test8git** [comment]
Downgrade "DocumentFormat.OpenXml" to 2.16.0 works for me

**Comment by dluc** [comment]
Is there an estimation for the next nuget release?

**Comment by GusBeare** [comment]
I just uninstalled the DocumentFormat.OpenXML package and ClosedXML works fine. I'm very confused. I thought it was a dependency?  I am sure it was required when I initially installed ClosedXML. I've tried removing it and reinstalling and it doesn't require OpenXML.  If it's no longer a dependency why does it show  DocumentFormat.OpenXML >=2.16.0 && < 3.0.0 in the list of dependencies?

**Comment by bradleypatton** [comment]
Just ran into this issue as well after upgrading OpenXml to 3.02. Any estimate on when this will be pushed to a release? Thanks

**Comment by BieleckiLtd** [comment]
> I just uninstalled the DocumentFormat.OpenXML package and ClosedXML works fine. I'm very confused. I thought it was a dependency? I am sure it was required when I initially installed ClosedXML. I've tried removing it and reinstalling and it doesn't require OpenXML. If it's no longer a dependency why does it show DocumentFormat.OpenXML >=2.16.0 && < 3.0.0 in the list of dependencies?

ClosedXML depends on DocumentFormat.OpenXML and will bring it as a transitive package. This means you do not need to include DocumentFormat.OpenXML in your project yourself. The problem arises when YOUR project also directly depends on DocumentFormat.OpenXML; in that case, you must pull the same version that ClosedXML depends on. As a reminder, the latest ClosedXML (0.102.2) depends on DocumentFormat.OpenXML (>= 2.16.0 && < 3.0.0).

**Comment by GusBeare** [comment]
Ah, many thanks for the explanation. I get it now.

**Comment by fadlan-ims** [comment]
![image](https://github.com/user-attachments/assets/a410856a-75b8-4a82-9fc8-a1b6d160de6e)
If it's the same as what I have, try changing the version

**Comment by igitur** [comment]
> ![image](https://private-user-images.githubusercontent.com/165238393/368000778-a410856a-75b8-4a82-9fc8-a1b6d160de6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTQxMTIsIm5iZiI6MTcyNjU1MzgxMiwicGF0aCI6Ii8xNjUyMzgzOTMvMzY4MDAwNzc4LWE0MTA4NTZhLTc1YjgtNGE4Mi05ZmM4LWExYjZkMTYwZGU2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwNjE2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODQ5MmM0NzcwZDA2NGNiMDUwYTc5MTFiZDNiZGQ3OWVhNjg1ZGEzYWQ1NjU1OTQzNDk5MzYyOTViNDA1NzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FXK5anRpyMFIRfh0PT3tbOodjKjV4hmDgrCGhF-lARo) If it's the same as what I have, try changing the version

`DocumentFormat.OpenXml` is a transitive dependency and will automatically be included. So my advice is not to specify it as a package reference at all, unless there's a very specific reason that you want to pin down its version number.
