### ISSUE TITLE
System.NotImplementedException in ConvertAnyValueToLegacyExpression when using array formula

### ISSUE THREAD

**Issue by gergodrazsdik** [ClosedXML/ClosedXML#2221]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.104.0-preview2

**What is the current behavior?**

Formula recalculation throws System.NotImplementedException when using specific array formula.

**What is the expected behavior or new feature?**

Not to throw exception and be able to read value from cell.

**Is this a regression from the previous version?**

It happens with 0.102.1 as well.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
    [Fact]
    public void Test_ConvertAnyValueToLegacyExpression_NotImplementedException()
    {
        // Arrange
        var workbook = new XLWorkbook();
        var sheet = workbook.AddWorksheet();
        sheet.Cell("A1").Value = "a";
        sheet.Cell("A2").Value = "a";
        sheet.Cell("A3").Value = "b";
        sheet.Cell("A4").Value = "b";
        sheet.Cell("A5").Value = "a";
        sheet.Range("A6").FormulaArrayA1 = "=MAX(ROW($1:5)*(A$1:A5=\"b\"))";
        
        // Act
        var actualValue = sheet.Cell("A6").Value;

        // Assert
        Assert.Equal("4", actualValue);
    }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[array_formula_error.xlsx](https://github.com/ClosedXML/ClosedXML/files/13460039/array_formula_error.xlsx)

**Comment by ChhayaGupta05** [comment]
Any solution?

**Comment by jahav** [comment]
Resolved through #2268, #2269, #2270.

**Comment by ChhayaGupta05** [comment]
@jahav So this issue will be resolved with ClosedXML -Version 0.104.0-preview2 library? or anything else we need to consider

**Comment by jahav** [comment]
@ChhayaGupta05 It will be resolved with new version of ClosedXML or you can use development package from appveyor https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts. 

Also, resolved is a strong word, but strongly mitigated yes. Legacy functions never supported errors (and plethora of other things), see #2270.

**Comment by ChhayaGupta05** [comment]
Hi @jahav , Tried today with  ClosedXML -Version 0.104.0-preview2 library but still getting same error

2024-02-05T06:22:42.342Z	fd664bd9-50eb-4679-81d5-933b4e9c4ba5	fail	System.NotImplementedException: The method or operation is not implemented.
   at ClosedXML.Excel.CalcEngine.FunctionDefinition.<>c.<ConvertAnyValueToLegacyExpression>b__16_11(XLError error) 
   
   Formula we using  for array funciton:

 [Fact]
    public void Test_ConvertAnyValueToLegacyExpression_NotImplementedException()
    {
        // Arrange
        var workbook = new XLWorkbook();
        var sheet = workbook.AddWorksheet();
        sheet.Cell("C5").Value = "50000";
        sheet.Cell("C6").Value = "50000";
        sheet.Cell("C7").Value = "50000";
        sheet.Cell("C8").Value = "50000";
        sheet.Cell("D5").Value = "10";
        sheet.Cell("C6").Value = "100";
        sheet.Cell("C7").Value = "20";
        sheet.Cell("C8").Value = "0";
        sheet.Range("A6").FormulaArrayA1 = "=SUM(IFERROR($C$5:$C$8/$D$5:$D$8;0))";
        
        // Act
        var actualValue = sheet.Cell("g5").Value;
        // Assert
        Assert.Equal("4", actualValue);
    }

[IFERROR-Function.xlsx](https://github.com/ClosedXML/ClosedXML/files/14162221/IFERROR-Function.xlsx)

**Comment by jahav** [comment]
@ChhayaGupta05 0.104.0-preview2 is 3 months old version that doesn't contain fix. Fix is only in develop branch that hasn't been released yet. See https://github.com/ClosedXML/ClosedXML/wiki/Development-Builds for how to use development build.

**Comment by ChhayaGupta05** [comment]
@jahav Thanks for quick reply. 

Any other closedxml version which is stable and not a preview release? We can use to resolve issue for Dynamic Array Formulas?

Regards,
Chhaya
