### ISSUE TITLE
0.104.1.0 not strongly named

### ISSUE THREAD

**Issue by craig-ten-uh** [ClosedXML/ClosedXML#2423]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.
_Does not apply; CI is older._

**Version of ClosedXML**

0.104.1

**What is the current behavior?**

DLL does not appear to be digitally signed. Getting following warning in our builds with latest version:

```##[warning]CSC(0,0): Warning CS8002: Referenced assembly 'ClosedXML, Version=0.104.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.```

Verified no Digital Signature in Windows and also using ```sn -v``` on both netstandard2.0 and netstandard2.1 dlls.

**What is the expected behavior or new feature?**

DLLs are digitally signed.

**Is this a regression from the previous version?**

Yes.

## Reproducibility

- Install nuget package globally.
- Run ```sn -v``` on either dll. E.g.:
   ```sn -v %userprofile%\.nuget\packages\closedxml\0.104.1\lib\netstandard2.1\ClosedXML.dll```
- Result: 
  ```C:\Users\<<user>>\.nuget\packages\closedxml\0.104.1\lib\netstandard2.1\ClosedXML.dll does not represent a strongly named assembly```

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
N/A

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
That's because rbush dependency is not strongly named. I asked (https://github.com/viceroypenguin/RBush/issues/51) , but it's not something author wants to support.

I will probably need to make a fork, joy of compliance driven development.

**Comment by Carlosjfr** [comment]
Hello!
We also intend to have the DLL with Strong Name Key, as our projects are all compiled this way, and without this we cannot reference this version 0.104.1.
It would be great to have the package with the signed DLL.

**Comment by Bjorgulv** [comment]
Hi.
We have the same problem and need a signed dll to our project.
Would be nice if this could be supported in next release.

**Comment by AndrewRDale** [comment]
Hi, I'm having a few problems with ClosedXML, do you have any ideas for a solution?

I've just installed the latest version of ClosedXML and I'm getting build issues / warnings in my project. 

BC41997
Referenced assembly 'ClosedXML, Version=0.104.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

I've added exception handling around the ClosedXML and now my clients are seeing errors in Event viewer.

Any help would be appreciated.

![ClosedXML Error](https://github.com/user-attachments/assets/5539d5d4-705d-4c2c-b19f-a86e925c252a)

**Comment by FRL-Lux** [comment]
Hi Jan,
Do you have an idea when the version 0.105.0 will be available?
Thanks a lot for your work!!!
Fred

**Comment by jahav** [comment]
Fixed in #2599.

**Comment by FRL-Lux** [comment]
Dear Sender,
Thank you for your email, I’m currently out of Office.
I will be back on Monday 6th January 2025

For more information, call +352 26 47 48 1

Best Regards,

**Comment by AndrewRDale** [comment]
Hi, Do you have an idea when the next version of ClosedXML will be published resolving the Strongly Named issue?
Regards
Andy

**Comment by rajtilakvyasmckinsey** [comment]
Hi @jahav  i am using ClosedXML, Version=0.104.1.0 
I have added both RBush 4.0.0 and RBush.Signed 4.0.0. but still getting strongly-named issue.

![Image](https://github.com/user-attachments/assets/d470ca09-02eb-4d69-bf8d-9043dd2d15d4)

**Comment by sir-wilhelm** [comment]
>@rajtilakvyasmckinsey [(ClosedXML/ClosedXML#2423)](https://github.com/ClosedXML/ClosedXML/issues/2423#issuecomment-2664522775)
>
>Hi [@jahav](https://github.com/jahav) i am using ClosedXML, Version=0.104.1.0
I have added both RBush 4.0.0 and RBush.Signed 4.0.0. but still getting strongly-named issue.
>
>[image.png (view on web)](https://github.com/user-attachments/assets/d470ca09-02eb-4d69-bf8d-9043dd2d15d4)

It's fixed in 0.105.0, but it's not been released / on nuget yet.

You can grab the RC version here: https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts

edit: looks like the rc was published to nuget, so you can pull it from there now (https://www.nuget.org/packages/ClosedXML/)
