### ISSUE TITLE
Resize table and delete columns from table

### ISSUE THREAD

**Issue by svetovich** [ClosedXML/ClosedXML#447]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**
When adding or removing columns to a table on a worksheet, the excel file is becoming corrupt because of something that is happening with the table.

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

**What is the expected behavior or new feature?**

**Did this work in previous versions of our tool?  Which versions?**

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)

[Testing.xlsx](https://github.com/ClosedXML/ClosedXML/files/1230991/Testing.xlsx)

**Code to reproduce problem:**
```vb.net
    Sub Main()
        Dim Table As New DataTable("Testing")

        With Table.Columns
            .Add("Test1")
            .Add("Test2")
            .Add("Test3")
            .Add("Test4")
            .Add("Test5")
        End With

        With Table.Rows
            .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
            .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
            .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
            .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
            .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")

            '.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
            '.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
            '.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
            '.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
            '.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
        End With

        Try
            Using WBook As New XLWorkbook(Path.Combine(My.Computer.FileSystem.SpecialDirectories.MyDocuments, "Testing.xlsx"))
                Dim WSheet As IXLWorksheet = WBook.Worksheets.Where(Function(ws) ws.Tables.Count > 0).FirstOrDefault
                Dim DTable As IXLTable = Nothing
                Dim RowIndex As Integer = 1

                If WSheet Is Nothing Then WSheet = WBook.Worksheets.Add("Table")

                WSheet.Cells.Clear()

                For Each Column As DataColumn In Table.Columns
                    WSheet.Cell(1, Column.Ordinal + 1).Value = Column.ColumnName
                Next

                For Each Row As DataRow In Table.Rows
                    RowIndex += 1

                    For Each Column As DataColumn In Table.Columns
                        WSheet.Cell(RowIndex, Column.Ordinal + 1).Value = Row(Column)
                    Next
                Next

                If WSheet.Tables.Count > 0 Then
                    DTable = WSheet.Tables.FirstOrDefault
                    DTable.RangeAddress.FirstAddress = WSheet.Cell(1, 1).Address
                    DTable.RangeAddress.LastAddress = WSheet.Cell(RowIndex, Table.Columns.Count).Address
                Else
                    DTable = WSheet.RangeUsed.CreateTable("Testing_Table")
                    DTable.Theme = XLTableTheme.TableStyleMedium2
                End If

                WSheet.Columns.AdjustToContents()

                WBook.Save()
            End Using
        Catch ex As Exception

        End Try
    End Sub
```

**Comment by igitur** [comment]
Attach the unmodified spreadsheet so that I can try run your code.

**Comment by svetovich** [comment]
It is attached below.

[Testing.xlsx](https://github.com/ClosedXML/ClosedXML/files/1231342/Testing.xlsx)

**Comment by kkazala** [comment]
I had a similar problem and i think I know how to solve it- maybe it will help you too. 

After adding a table to the worksheet, I want to delete one of the columns. 
I first remove it from the range and then resize the table:

DataTable table= getTable();
int colIndex=10; //for example...
using (var ws = wb.Worksheets.Add(table, table.TableName))
{
          var rngData = ws.Range(ws.FirstCellUsed(), ws.LastCellUsed());
          IXLRangeColumn absoluteUrlCol = rngData.Column(colIndex);

          //remove the column from the range
          ws.Range(absoluteUrlCol.RangeAddress).Delete(XLShiftDeletedCells.ShiftCellsLeft);

          //resize the table
          var table=ws.Tables.FirstOrDefault();
          table.RangeAddress.FirstAddress = ws.FirstCellUsed().Address;
          table.RangeAddress.LastAddress = ws.LastCellUsed().Address;
}

Not sure if it's best practice, but works :)

**Comment by igitur** [comment]
@svetovich I still can't reproduce your issue. I can open `Testing.xlsx`, run the code on it, and save a file that is not corrupt.

Try with the latest `develop` branch from the repository. If you can reproduce the problem, post a full code sample that I can paste as is into a console application and run to show the error.

**Comment by igitur** [comment]
@kkazala I can reproduce the issue with your code sample. Will look into it.

**Comment by igitur** [comment]
Fixed in #452. Refer to the new unit test for how to correctly delete columns from tables:

```c#
public void CanDeleteTableField()
{
    var l = new List<TestObjectWithAttributes>()
    {
        new TestObjectWithAttributes() { Column1 = "a", Column2 = "b", MyField = 4, UnOrderedColumn = 999 },
        new TestObjectWithAttributes() { Column1 = "c", Column2 = "d", MyField = 5, UnOrderedColumn = 777 }
    };

    using (var wb = new XLWorkbook())
    {
        var ws = wb.AddWorksheet("Sheet1");
        var table = ws.FirstCell().InsertTable(l);

        // Delete column from table. Don't use the underlying `Range`
        table.Column("C").Delete();

        Assert.AreEqual(3, table.Fields.Count());

        Assert.AreEqual("FirstColumn", table.Fields.First().Name);
        Assert.AreEqual(0, table.Fields.First().Index);

        Assert.AreEqual("UnOrderedColumn", table.Fields.Last().Name);
        Assert.AreEqual(2, table.Fields.Last().Index);
    }
}
```

**Comment by igitur** [comment]
When the PR is implemented, there will be 2 ways to delete a field/column:
```
table.Column("C").Delete();
```

and 

```
table.Field("SomeFieldNotProperty").Delete();
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.

**Comment by svetovich** [comment]
I apologize it took me so long to get back to this but I'm still experiencing an issue with the latest 0.89.0 beta.  Unfortunately I can't use Column.Delete because I don't know exactly what columns will be deleted, which is why I need resize the table to accommodate the updated data.  The code below is what I've been using to test, updating the ColCount variable in the Main sub to change the number of columns in the Excel table.  Below is a step-by-step process that I follow to hit the error

1. I start with 5 columns and run the code which creates the Excel file
2. Then I move to 4 columns and run the code again which updates the Excel file, no issues
3. I then go back to 5 columns and run the code, which is where I'm experiencing the issue

`    Imports System.IO
    Imports ClosedXML.Excel
    
    Module Module2
        Sub Main()
            Dim FilePath As String = Path.Combine(My.Computer.FileSystem.SpecialDirectories.Desktop, "Testing.xlsx")
            Dim Table As New DataTable("Testing")
            Dim ColCount As Integer = 5
    
            With Table.Columns
                For i As Integer = 1 To ColCount
                    .Add("Test" & i)
                Next
            End With
    
            With Table.Rows
                For i As Integer = 1 To 10
                    Select Case ColCount
                        Case = 5 : .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
                        Case = 4 : .Add("Testing 1", "Testing 2", "Testing 3", "Testing 4")
                    End Select
                Next
            End With
    
            Select Case File.Exists(FilePath)
                Case True : Update(Table, FilePath)
                Case Else : Create(Table, FilePath)
            End Select
        End Sub
    
        Sub Create(ByVal dt As DataTable, ByVal Filepath As String)
            Using WBook As New XLWorkbook()
                Dim Sheet As IXLWorksheet = WBook.Worksheets.Add("Table")
                Dim RowCount As Integer = dt.Rows.Count
                Dim RowIndex As Integer = 1
                Dim ColIndex As Integer = 0
    
                For Each Column As DataColumn In dt.Columns
                    ColIndex = Column.Ordinal + 1
                    Sheet.Cell(RowIndex, ColIndex).Value = Column.ColumnName
                Next
    
                For Each Row As DataRow In dt.Rows
                    RowIndex += 1
    
                    For Each Column As DataColumn In dt.Columns
                        ColIndex = Column.Ordinal + 1
                        Sheet.Cell(RowIndex, ColIndex).Value = Row(Column)
                    Next
                Next
    
                Dim Table As IXLTable = Sheet.RangeUsed.CreateTable("Test")
    
                Table.Theme = XLTableTheme.TableStyleMedium2
                Sheet.Columns.AdjustToContents()
    
                WBook.SaveAs(Filepath)
            End Using
        End Sub
    
        Sub Update(ByVal dt As DataTable, ByVal FilePath As String)
            Using WBook As New XLWorkbook(FilePath)
                Dim Sheet As IXLWorksheet = WBook.Worksheets.Where(Function(ws) ws.Tables.Count > 0).FirstOrDefault
                Dim Table As IXLTable = Sheet.Tables.FirstOrDefault
                Dim RowCount As Integer = dt.Rows.Count
                Dim RowIndex As Integer = 1
                Dim ColIndex As Integer = 0
    
                Sheet.Cells.Clear()
    
                For Each Column As DataColumn In dt.Columns
                    ColIndex = Column.Ordinal + 1
                    Sheet.Cell(RowIndex, ColIndex).Value = Column.ColumnName
                Next
    
                For Each Row As DataRow In dt.Rows
                    RowIndex += 1
    
                    For Each Column As DataColumn In dt.Columns
                        ColIndex = Column.Ordinal + 1
                        Sheet.Cell(RowIndex, ColIndex).Value = Row(Column)
                    Next
                Next
    
                Table.RangeAddress.FirstAddress = Sheet.Cell(1, 1).Address
                Table.RangeAddress.LastAddress = Sheet.Cell(RowIndex, ColIndex).Address
                Sheet.Columns.AdjustToContents()
    
                WBook.Save()
            End Using
        End Sub
    End Module`

**Comment by igitur** [comment]
@svetovich Your code sample is way too much. I need the smallest possible code sample to reproduce the problem. I don't want all your application logic. See https://stackoverflow.com/help/mcve for a description of what I need.

**Comment by svetovich** [comment]
My apologies.  I trimmed it down as much as I could to still produce the error.  I hope it's simple enough for testing.  I've also attached a sample spreadsheet.  I'm getting an error at the WBook.Save() event and the file is becoming corrupted.  Upon being repaired the table part is removed and the fifth column isn't there.

`    Imports System.IO
    Imports ClosedXML.Excel
    
    Module Module1
        Sub Main()
            Dim FilePath As String = Path.Combine(My.Computer.FileSystem.SpecialDirectories.Desktop, "Testing.xlsx")
            Dim dt As New DataTable("Testing")
    
            For i As Integer = 1 To 5
                dt.Columns.Add("Test" & i)
            Next
    
            For i As Integer = 1 To 10
                dt.Rows.Add("Testing 1", "Testing 2", "Testing 3", "Testing 4", "Testing 5")
            Next
    
            Using WBook As New XLWorkbook(FilePath)
                Dim Sheet As IXLWorksheet = WBook.Worksheets.Where(Function(ws) ws.Tables.Count > 0).FirstOrDefault
                Dim Table As IXLTable = Sheet.Tables.FirstOrDefault
                Dim RowCount As Integer = dt.Rows.Count
                Dim RowIndex As Integer = 1
                Dim ColIndex As Integer = 0
    
                Sheet.Cells.Clear()
    
                For Each Column As DataColumn In dt.Columns
                    ColIndex = Column.Ordinal + 1
                    Sheet.Cell(RowIndex, ColIndex).Value = Column.ColumnName
                Next
    
                For Each Row As DataRow In dt.Rows
                    RowIndex += 1
    
                    For Each Column As DataColumn In dt.Columns
                        ColIndex = Column.Ordinal + 1
                        Sheet.Cell(RowIndex, ColIndex).Value = Row(Column)
                    Next
                Next
    
                Table.RangeAddress.FirstAddress = Sheet.Cell(1, 1).Address
                Table.RangeAddress.LastAddress = Sheet.Cell(RowIndex, ColIndex).Address
                Sheet.Columns.AdjustToContents()
    
                WBook.Save()
            End Using
        End Sub
    End Module
`

[Testing.xlsx](https://github.com/ClosedXML/ClosedXML/files/1271098/Testing.xlsx)

**Comment by vbjay** [comment]
https://github.com/closedxml/closedxml/wiki/Adding-DataTable-as-Worksheet

https://github.com/closedxml/closedxml/wiki/Inserting-Data

**Comment by svetovich** [comment]
I know how to add a new datatable to a worksheet, that's not my issue. My issue is resizing an existing table on a worksheet when additional columns are added. I have other components, namely Pivot Tables, based on this Excel table so it's not an option to delete it and just add a new table.

**Comment by vbjay** [comment]
My point is that you could have skipped the loop.

  // From a DataTable
  var dataTable = GetTable();
  ws.Cell(6, 1).Value = "From DataTable";
  ws.Range(6, 1, 6, 4).Merge().AddToNamed("Titles");
  var rangeWithData = ws.Cell(7, 1).InsertData(dataTable.AsEnumerable());

Also you can use the table methods to set the size ahead of time to how
many rows.

Also how does your sample remove a column?

**Comment by svetovich** [comment]
I understand how that method could avoid using the loop, and it is something I will look into. But I don't understand how it helps with resizing the actual table to accommodate the new data when new columns are introduced?

Adjusting the table for new rows has never been a problem, only when adding new columns to an existing table. 

My example doesn't demonstrate removing a column because because with the 0.89.0-beta1 I'm no longer experiencing an issue when removing columns, only when adding them.

**Comment by vbjay** [comment]
I see.

**Comment by igitur** [comment]
Ok, I think I get what you want to do now. Are you sure you can't delete the table, create a new one and have your pivot tables point to the new table? I haven't checked. 

I'll also try to create a `table.ChangeRange()` method to redefine an existing table, but that might take a while. Excel files are easily corruptible if you mess up a table.

**Comment by svetovich** [comment]
I probably could delete it and recreate it but I ran into issues there as well. When I initially tried that the table.delete function didn't seem to work probably, unless I was doing something wrong which is a definite possibility. Also, because the pivot table functionality is still "experimental", looping through all of my other worksheets to update the pivot table source range proved problematic. Either the code couldn't always find the pivot tables, even though they were definitely there, or updating the source range (it would be nice to set the table itself as the source rather than just a range) would cause issues with the pivot table layout and I would need to recreate that too. 

Trust me, I've been through the gambit with trying to make this work, even trying other libraries. I much prefer to stick with ClosedXML because of the great documentation and wick response time to questions/issues like this.

**Comment by igitur** [comment]
@svetovich Try the latest CI build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.520/artifacts

There is a new `XLTable.Resize(range)` method that you could try out.

**Comment by svetovich** [comment]
This is working very well!  I have done multiple tests with no apparent issues.  Thank you very much for your help and all of your work.  Looking forward to when this is published!

**Comment by igitur** [comment]
https://www.nuget.org/packages/ClosedXML/0.90.0-beta2 is released and should include the fix for this issue.

**Comment by mendozajay** [comment]
How about deleting multiple columns like, column 1, 5, 26 and 30 ?
