### ISSUE TITLE
Existing charts in template files are missing after save

### ISSUE THREAD

**Issue by hkoestin** [ClosedXML/ClosedXML#869]
Hello,

there seems to be a problem with the latest version of ClosedXML regarding charts in existing XLSX files.

I have a chart in a template, which consumes data from a different worksheet. 
When I only use ClosedXML to update the data, after saving the file, the chart is gone.

Version used: 0.92.1

Maybe it is also due to one of the dependencies (DocumentFormat.OpenXml or FastMember.Signed), which causes this bug.

Cheers
Harald

**Comment by igitur** [comment]
Complete the full issue template.

**Comment by irtimclark** [comment]
Yeah, this one hit me too. It's fixed in the 0.93 beta.  https://github.com/ClosedXML/ClosedXML/commit/034e8e02ff229aaf67922859278e1abc8e88bda4

**Comment by vinhladn** [comment]
Hi everyone,

I have already a problem same as above `hkoestin commented on 22 May 2018`
`I have a chart in a template, which consumes data from a different worksheet.
When I only use ClosedXML to update the data, after saving the file, the chart is gone.
Version used: 0.95.3`

Anyone can help to guide to me how to save the file with exists chart from a template? Very much appreciate for your help

Thanks

**Comment by vinhladn** [comment]
> Yeah, this one hit me too. It's fixed in the 0.93 beta. [034e8e0](https://github.com/ClosedXML/ClosedXML/commit/034e8e02ff229aaf67922859278e1abc8e88bda4)

Hi irtimclark,

Could you share your solution for this problem at comment `hkoestin commented on 22 May 2018`? 

Thank you so much

**Comment by Balazzzska** [comment]
Hi,
The issue still exists in the currently latest version (0.95.0). I did try all the versions back to 0.80.1 (including version 0.93 as mentioned by irtimclark) without any success.

**Comment by DavidDeSloovere** [comment]
I found out that you can't use the `XLWorkbook.OpenFromTemplate(` method because that will drop the chart.
You have to new up the `XLWorkbook` using the path in the `ctor`.
